### ISSUE TITLE
Initial reimplementation of OAI harvest daemon

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio-oaiharvester#1]
We need a Celery task that we can schedule regularly (or one-off) to do an OAI-PMH request with given or predefined settings (e.g. from a OaiHarvest model) and handle the output. 

The output can optionally be passed to a workflow (single or multiple records), or simply written to a file or stdout.

For the actual request we can leverage the cool [sickle](https://sickle.readthedocs.org/en/latest/) package to build an API that makes available the appropriate features to make an OAI-PMH request in Invenio. The parameters for the request can be either (1) a provided OaiHarvest object or (2) direct parameters.

- [x] add API to make OAI-PMH requests through Sickle (`api.py`)
- [x] add a Celery task that will make a request and process the output as described above (`tasks/__init__.py`)
- [x] add a manager to perform one-shot requests and list predefined configurations (`manager.py`)
- [x] remove legacy "mother" workflows (`workflows/*.py`) and any other dead code.

@Lilykos and @jalavik will look at this.

CC @kaplun @lnielsen

**Comment by jirikuncar** [comment]
@kaplun @jalavik can you create WIP pull-request so we see the ongoing work?

**Comment by lnielsen** [comment]
+1 for sickle (btw, I know the main author of the package from OpenAIRE)

Additionally. It would be great if the harvesting is generic enough to deal with not only records. E.g. on Zenodo I'm harvesting EC grants: https://github.com/zenodo/zenodo/blob/master/zenodo/modules/grants/contrib/openaire.py

**Comment by jalavik** [comment]
@lnielsen Sure. It won't be expecting anything else than OAI-PMH "records" so to speak which is then feeded to a custom workflow, disk or stdout. All scheduled in process or in Celery through the manager or celery-beat.

@jirikuncar Added WIP, albeit not very exciting yet, but later today we will add more goodies!
